# -*- coding: utf-8 -*-
"""CD_taller1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bHm2Eo6_5mbk6wcYwOF-31SdcsJIXpeA
"""

import numpy as np

x = np.array([3, 7, 8, 2, 11, 6])
y = np.array([17, 14, 14, 19, 6, 16])

n = len(x)

sum_x = sum(x)
sum_y = sum(y)
print(sum_x)
print(sum_y)

sum_xy = sum(x*y)
sum_x_2 = sum(x**2)
print(sum_xy)
print(sum_x_2)

prom_x = sum(x)/n
prom_y = sum(y)/n

m = ((n*sum_xy) - (sum_x*sum_y))/((n*sum_x_2)-((sum_x)**2))

b = prom_y - (m * prom_x)

print(m)
print(b)